[package]
name = "exampleproxy"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.43.0", features = ["full"] }
hyper = { version = "0.14.32", features = ["full"] }
tokio-stream = { version = "0.1.17", features = ["full"] }